baseURL = 'https://blog.mindfulknowledges.com/'
languageCode = 'en-us'
title = 'Code dev blog'

paginate = 4

[params]
  description = "The fastest blog"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"